s1:
  program: program
  digest:
  rules:
    - table: MyIngress.ipv4_exact
      keys:
        - value: 10.0.1.1 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 00:01:00:00:01:00 #mac
        - 1
    - table: MyIngress.ipv4_exact
      keys:
        - value: 10.0.1.2 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 00:01:00:00:02:00 #mac
        - 1
    - table: MyIngress.ipv4_exact
      keys:
        - value: 10.0.2.1 #h3
      action: MyIngress.ipv4_forward
      action_param:
        - 00:02:00:00:01:00 #mac
        - 2
    - table: MyIngress.ipv4_exact
      keys:
        - value: 10.0.2.2 #h4
      action: MyIngress.ipv4_forward
      action_param:
        - 00:02:00:00:02:00 #mac
        - 2
    - table: MyIngress.ipv4_lpm
      keys:
        - value: 10.0.3.0/24 #h5h6
      action: MyIngress.ipv4_forward
      action_param:
        - 00:00:00:00:00:05 #mac
        - 3
    - table: MyIngress.arp_exact
      keys:
        - value: 10.0.1.1 #h1
      action: MyIngress.arp_reply
      action_param:
        - 00:00:00:00:00:01 #mac
    - table: MyIngress.arp_exact
      keys:
        - value: 10.0.1.2 #h2
      action: MyIngress.arp_reply
      action_param:
        - 00:00:00:00:00:01 #mac
    - table: MyIngress.arp_exact
      keys:
        - value: 10.0.2.1 #h3
      action: MyIngress.arp_reply
      action_param:
        - 00:00:00:00:00:02 #mac
    - table: MyIngress.arp_exact
      keys:
        - value: 10.0.2.2 #h4
      action: MyIngress.arp_reply
      action_param:
        - 00:00:00:00:00:02 #mac
        

